### ISSUE TITLE
Dont even works

### ISSUE THREAD

**Issue by Orafilynie** [Fabi019/CTPowderTracker#1]
No Overlay showing at all

**Comment by Fabi019** [comment]
Thank you for the feedback.
If you download the module while you are in a world, the overlay is not immediately shown as it does not constantly update its state. To show the overlay it requires you to either rejoin your current world/server or type "/powdertracker sync" in chat. This has to be done only once after you ran the import command.
Please let me know if that fixes the problem.

**Comment by Orafilynie** [comment]
didnt did anything

**Comment by Fabi019** [comment]
Am I correct in the assumption that the mod is indeed installed and thus the "/powdertracker" command does return the help text?
If that is the case the only other thing I could imagine is some kind of incompatibilty to a different installed module as I just tried it out myself on I a fresh installation with no other modules and it did work correctly.
If you want me to look if that is the case, I would appreciate if you can send me a list of your installed modules on discord to Fabi019#1339.

**Comment by Fabi019** [comment]
Closed as stale/not reproducible.
